### ISSUE TITLE
Qui est DSams ?

### ISSUE THREAD

**Issue by ArnaudLigny** [GouvernementFR/RepubliqueNumerique#8]
Chaque commit est systématiquement commenté par un certain @DSams : qui saurait dire qui est cette personne et son rôle ?

Merci d'avance.

**Comment by DSams** [comment]
Euh, c'est pas le principe du site ? Je suis un contributeur de République-numérique.fr, pourquoi? Et vous, qui êtes-vous et quel est votre rôle ?

**Comment by ArnaudLigny** [comment]
Bonjour, je me demandais simplement si vous étiez un "bot" ou un humain :-)

Pour en savoir plus sur moi il vous suffit de cliquer sur mon avatar et vous tomberez sur mon profil GitHub : prénom, nom, localisation et site perso.

En aucun je n'ai souhaité être vindicatif. Bonne journée.

**Comment by DSams** [comment]
Un bot non seulement capable d'écrire, mais aussi de commenter des textes de loi ;-) A quand l'écriture automatique du droit ? Bonne journée

**Comment by julien-c** [comment]
Merci à tous pour vos contributions (y compris @DSams !) qui sont très appréciées, et lues avec attention.
